DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;

CREATE TABLE person (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  full_name TEXT UNIQUE NOT NULL,
  phone_number TEXT UNIQUE NOT NULL,
  email TEXT NOT NULL
);